### ISSUE TITLE
add images to bullets, currently doesn't look good

### ISSUE THREAD

**Issue by spickering-git** [trendmanagement/new_website#16]
![image](https://cloud.githubusercontent.com/assets/18487289/25493358/bb18a264-2b2a-11e7-8b9d-dfaea1b0511e.png)

**Comment by DinamickaDevelopment** [comment]
![image](https://cloud.githubusercontent.com/assets/12965606/25524728/7e5c52c2-2c14-11e7-8e7d-e1fce6a1c495.png)

do you mean these images from the previous design version?

**Comment by spickering-git** [comment]
These should not be bullet points.
These points should look more like:
![image](https://cloud.githubusercontent.com/assets/18487289/25911131/92143a94-3567-11e7-9039-69c304f7c541.png)
![image](https://cloud.githubusercontent.com/assets/18487289/25911138/9bb22340-3567-11e7-9a71-5bcaba8ed039.png)
![image](https://cloud.githubusercontent.com/assets/18487289/25911159/ab99602a-3567-11e7-9494-42ee86eb5ae1.png)

Each point could have an image associated with it in its own section.
I re downloaded some of the photos from our account at Getty Images
https://app.box.com/s/q0mwtj22v33kaap7iseacv86g8r4gxih that could be used here.
