### ISSUE TITLE
disclaimer should show up as soon as user lands on home page

### ISSUE THREAD

**Issue by spickering-git** [trendmanagement/new_website#17]
disclaimer should show up as soon as user lands on home page

![image](https://cloud.githubusercontent.com/assets/18487289/25493600/a01c834e-2b2b-11e7-8e4f-1d176448ac76.png)

then goes away once they click accept, and does not show up again for that user.

**Comment by DinamickaDevelopment** [comment]
Should user get Disclaimer popup every time that he get on Home page?

**Comment by spickering-git** [comment]
The user should see this Terms of Use the on the first time they go to the page.

**Comment by DinamickaDevelopment** [comment]
Yes, for now it has logic like you have described, when new user get to the home page he will get Term of Use pop up, after he accept it, it wouldn't show again in vistit in next time, or on reload page.
