### ISSUE TITLE
main page

### ISSUE THREAD

**Issue by spickering-git** [trendmanagement/new_website#21]
1. change the family office image to something like
![image](https://cloud.githubusercontent.com/assets/18487289/26603565/1a055706-453c-11e7-883b-8ea064d8369c.png)
a tree covered path symbolizing guidance

1. Can you also adjust all of the text so that it is visible
in this example the text is not visible because of the white cup in the image
![image](https://cloud.githubusercontent.com/assets/18487289/26603607/42c58576-453c-11e7-81d6-1fd44462a8b5.png)

1. We were thinking the CTA image (commodity trading advisors) could be some sort of combination of 
![image](https://cloud.githubusercontent.com/assets/18487289/26603857/2cccdeb2-453d-11e7-9cc9-165daecadc0f.png)
and
![image](https://cloud.githubusercontent.com/assets/18487289/26603867/39bdcb2c-453d-11e7-8c95-87ed746cb338.png)
Not sure if that will work.

1. Could you change language on this frame
![image](https://cloud.githubusercontent.com/assets/18487289/26603954/8bfc659c-453d-11e7-8e93-e3b6e2b9c05b.png)

to: 'Enter the World of Modern Algorithmic Investing'

**Comment by DinamickaDevelopment** [comment]
done
