### ISSUE TITLE
change links

### ISSUE THREAD

**Issue by spickering-git** [trendmanagement/new_website#25]
under the **SERVICES** menu
1.
![image](https://user-images.githubusercontent.com/18487289/26844287-c01225c8-4aa7-11e7-8233-cf6a099fd184.png)

please remove mouse over and link formatting from **TMQR EXO INDEX**

please move **TMQR Exo Index Attributes** up above  **Indexation Approach**

rename  **TMQR Exo Index Attributes** to  **TMQR Exo Index Facts / Attributes**

2.
![image](https://user-images.githubusercontent.com/18487289/26842820-f38ab6ae-4aa2-11e7-979d-138be5293513.png)
TMQR ALPHA PROJECT -> should link to a page with following text:

> This enterprise seeks to quantify the sources of active management or "Alpha" through the creation
> of active trading strategy indexes linked to such factors as:
> a) Trend/Momentum
> b) Seasonality
> c) Carry
> d) Volatility/Option Premium Collection
![image](https://user-images.githubusercontent.com/18487289/26844827-8d942b44-4aa9-11e7-8d26-d32738d55d3e.png)
with a button at bottom **FIND OUT MORE** that takes the user to http://trendmanage.azurewebsites.net/tell-about

3.
![image](https://user-images.githubusercontent.com/18487289/26842899-34c450a8-4aa3-11e7-8c1f-b1bf1046939d.png)

TMQR ROBO HEDGER / TMQR ROBO MANAGER -> should link to a page with the following text:

> TMQR Robo Hedger / TMQR Robo Manager
> Allows users to design investment / hedging algorithms which can be linked to separate manged accounts for automated electronic execution. 
![image](https://user-images.githubusercontent.com/18487289/26844827-8d942b44-4aa9-11e7-8d26-d32738d55d3e.png)
with a button at bottom **FIND OUT MORE** that takes the user to http://trendmanage.azurewebsites.net/tell-about

4.
![image](https://user-images.githubusercontent.com/18487289/26842956-71acc630-4aa3-11e7-9b85-ed3c805c15fe.png)
the word 'SERVICES' needs to have spelling corrected
TMQR TECHNOLOGY SERVICES -> should link to page with the following text

> TMQR Technology Services is a custom consulting service where our team of quants and finance
> experts help design and deploy trading and data management solutions to meet the needs of
> market makers, investment advisers, fund sponsors or proprietary trading groups.
![image](https://user-images.githubusercontent.com/18487289/26844827-8d942b44-4aa9-11e7-8d26-d32738d55d3e.png)
with a button at bottom **FIND OUT MORE** that takes the user to http://trendmanage.azurewebsites.net/tell-about

5.
![image](https://user-images.githubusercontent.com/18487289/26844421-347bb1cc-4aa8-11e7-9486-b76dc22f50c5.png)

VALUE PROPOSITIONS -> should link to page with the following text

> Value / Unique Selling proposition :  TMQR offers a unique, scale-able options (derivatives ) research and automated trading platform where sophisticated firms can develop, test, deploy and refine algorithmic investment, hedging risk, or trading strategies in the global exchange traded derivatives markets.

6.
![image](https://user-images.githubusercontent.com/18487289/26844564-af70fb12-4aa8-11e7-9217-05676fe2867e.png)

PRODUCTS should link to:
![image](https://user-images.githubusercontent.com/18487289/26844609-d90472e2-4aa8-11e7-8a16-ca1323c51ef3.png)

**Comment by DinamickaDevelopment** [comment]
Done
