### ISSUE TITLE
finishing up

### ISSUE THREAD

**Issue by spickering-git** [trendmanagement/new_website#26]
1. please update phone number to (312) 957-7191 and email address to najoyce@tml1.com
![image](https://user-images.githubusercontent.com/18487289/27054147-d020a1c0-4f74-11e7-8e1d-11eab15f10f1.png)

1. Can you just make the CONTACT US link take you to the About Us page
![image](https://user-images.githubusercontent.com/18487289/27054271-42b17124-4f75-11e7-855b-2ac544d54de4.png)

1. once these are selected
![image](https://user-images.githubusercontent.com/18487289/27054609-64733238-4f76-11e7-8ed8-2210ec4e0db3.png)

should take you to Tell Us About Yourself
![image](https://user-images.githubusercontent.com/18487289/27054680-97ab78b8-4f76-11e7-84f9-a3714adf2444.png)

**Comment by DinamickaDevelopment** [comment]
Done
